[theme]
base = "light"
primaryColor = "#2E7BCF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#111111"

[server]
headless = true
port = 8501
enableCORS = false

[global]
name = "Antibiotic Resistance Detector UI"
